### ISSUE TITLE
Wiki | grammatical error

### ISSUE THREAD

**Issue by jedimomheather** [PowerAppster/PowerAppsPumpkinFramework#2]
Word 'continents' should be 'consonants' in 'Standard naming conventions for controls...' picture

<img width="428" alt="image" src="https://user-images.githubusercontent.com/63321930/203825186-46b0b394-4092-4b29-b392-4b8f432eab2f.png">

**Comment by KeithWhatling** [comment]
Thank you, I have changed that and added a bit more clarity around the selection of letters.
